# The URL the site will be built for
base_url = "https://vcfxb.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

light_theme = "github-light"
dark_theme = "github-dark"

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
# Get themes from https://textmate-grammars-themes.netlify.app/
extra_themes = []

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the RFC3339 datetime of the page in the search index
include_date = true
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# Put all your custom variables here
author = "Venus Xeon-Blonde"
